Algoritmo "meu primeiro algoritmo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Salvar Vidas (Dev)
// Autor(a)    : Rodrigo Oliveira
// Data atual  : 08/06/2020
Var
// Seção de Declarações das variáveis 
 nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nota <- 100
     escreva ("Resultado:", nota)
Fimalgoritmo